/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oscase2;

import javax.swing.JOptionPane;

/**
 *
 * @author casti
 */
public class MainFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame2
     */
    public MainFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        fcfsButton = new javax.swing.JButton();
        sstfButton = new javax.swing.JButton();
        scanButton = new javax.swing.JButton();
        cscanButton = new javax.swing.JButton();
        lookButton = new javax.swing.JButton();
        clookButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        homebg = new javax.swing.JLabel();
        fcfsPanel = new javax.swing.JPanel();
        diskTextField = new javax.swing.JTextField();
        diskButton = new javax.swing.JButton();
        clearDiskButton = new javax.swing.JButton();
        requestsTextField = new javax.swing.JTextField();
        headButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        headTextField = new javax.swing.JTextField();
        ioRequestsButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        calculateButton = new javax.swing.JButton();
        tracksLabel = new javax.swing.JLabel();
        graphScrollPane = new javax.swing.JScrollPane();
        graphPanel10 = new javax.swing.JPanel();
        FCFSTableScrollPane = new javax.swing.JScrollPane();
        FCFSTable10 = new javax.swing.JTable();
        resultsTextAreaScrollPane = new javax.swing.JScrollPane();
        resultsTextArea10 = new javax.swing.JTextArea();
        fcfsbg = new javax.swing.JLabel();
        sstfPanel = new javax.swing.JPanel();
        diskTextField1 = new javax.swing.JTextField();
        diskButton1 = new javax.swing.JButton();
        clearDiskButton1 = new javax.swing.JButton();
        requestsTextField1 = new javax.swing.JTextField();
        headButton1 = new javax.swing.JButton();
        clearButton1 = new javax.swing.JButton();
        headTextField1 = new javax.swing.JTextField();
        ioRequestsButton1 = new javax.swing.JButton();
        resetButton1 = new javax.swing.JButton();
        calculateButton1 = new javax.swing.JButton();
        tracksLabel1 = new javax.swing.JLabel();
        graphScrollPane1 = new javax.swing.JScrollPane();
        graphPanel9 = new javax.swing.JPanel();
        FCFSTableScrollPane1 = new javax.swing.JScrollPane();
        FCFSTable9 = new javax.swing.JTable();
        resultsTextAreaScrollPane1 = new javax.swing.JScrollPane();
        resultsTextArea9 = new javax.swing.JTextArea();
        sstfbg = new javax.swing.JLabel();
        scanPanel = new javax.swing.JPanel();
        diskTextField2 = new javax.swing.JTextField();
        diskButton2 = new javax.swing.JButton();
        clearDiskButton2 = new javax.swing.JButton();
        requestsTextField2 = new javax.swing.JTextField();
        headButton2 = new javax.swing.JButton();
        clearButton2 = new javax.swing.JButton();
        headTextField2 = new javax.swing.JTextField();
        ioRequestsButton2 = new javax.swing.JButton();
        resetButton2 = new javax.swing.JButton();
        calculateButton2 = new javax.swing.JButton();
        tracksLabel2 = new javax.swing.JLabel();
        graphScrollPane2 = new javax.swing.JScrollPane();
        graphPanel8 = new javax.swing.JPanel();
        FCFSTableScrollPane2 = new javax.swing.JScrollPane();
        FCFSTable8 = new javax.swing.JTable();
        resultsTextAreaScrollPane2 = new javax.swing.JScrollPane();
        resultsTextArea8 = new javax.swing.JTextArea();
        scanbg = new javax.swing.JLabel();
        cscanPanel = new javax.swing.JPanel();
        diskTextField3 = new javax.swing.JTextField();
        diskButton3 = new javax.swing.JButton();
        clearDiskButton3 = new javax.swing.JButton();
        requestsTextField3 = new javax.swing.JTextField();
        headButton3 = new javax.swing.JButton();
        clearButton3 = new javax.swing.JButton();
        headTextField3 = new javax.swing.JTextField();
        ioRequestsButton3 = new javax.swing.JButton();
        resetButton3 = new javax.swing.JButton();
        calculateButton3 = new javax.swing.JButton();
        tracksLabel3 = new javax.swing.JLabel();
        graphScrollPane3 = new javax.swing.JScrollPane();
        graphPanel7 = new javax.swing.JPanel();
        FCFSTableScrollPane3 = new javax.swing.JScrollPane();
        FCFSTable7 = new javax.swing.JTable();
        resultsTextAreaScrollPane3 = new javax.swing.JScrollPane();
        resultsTextArea7 = new javax.swing.JTextArea();
        cscanbg = new javax.swing.JLabel();
        lookPanel = new javax.swing.JPanel();
        diskTextField4 = new javax.swing.JTextField();
        diskButton4 = new javax.swing.JButton();
        clearDiskButton4 = new javax.swing.JButton();
        requestsTextField4 = new javax.swing.JTextField();
        headButton4 = new javax.swing.JButton();
        clearButton4 = new javax.swing.JButton();
        headTextField4 = new javax.swing.JTextField();
        ioRequestsButton4 = new javax.swing.JButton();
        resetButton4 = new javax.swing.JButton();
        calculateButton4 = new javax.swing.JButton();
        tracksLabel4 = new javax.swing.JLabel();
        graphScrollPane4 = new javax.swing.JScrollPane();
        graphPanel6 = new javax.swing.JPanel();
        FCFSTableScrollPane4 = new javax.swing.JScrollPane();
        FCFSTable6 = new javax.swing.JTable();
        resultsTextAreaScrollPane4 = new javax.swing.JScrollPane();
        resultsTextArea6 = new javax.swing.JTextArea();
        lookbg = new javax.swing.JLabel();
        clookPanel = new javax.swing.JPanel();
        diskTextField5 = new javax.swing.JTextField();
        diskButton5 = new javax.swing.JButton();
        clearDiskButton5 = new javax.swing.JButton();
        requestsTextField5 = new javax.swing.JTextField();
        headButton5 = new javax.swing.JButton();
        clearButton5 = new javax.swing.JButton();
        headTextField5 = new javax.swing.JTextField();
        ioRequestsButton5 = new javax.swing.JButton();
        resetButton5 = new javax.swing.JButton();
        calculateButton5 = new javax.swing.JButton();
        tracksLabel5 = new javax.swing.JLabel();
        graphScrollPane5 = new javax.swing.JScrollPane();
        graphPanel5 = new javax.swing.JPanel();
        FCFSTableScrollPane5 = new javax.swing.JScrollPane();
        FCFSTable5 = new javax.swing.JTable();
        resultsTextAreaScrollPane5 = new javax.swing.JScrollPane();
        resultsTextArea5 = new javax.swing.JTextArea();
        clookbg = new javax.swing.JLabel();
        mainbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(950, 600));

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setOpaque(false);
        sidePanel.setLayout(new java.awt.GridLayout(8, 0, 2, 2));

        homeButton.setBackground(new java.awt.Color(43, 137, 253));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/homeicon.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setContentAreaFilled(false);
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButtonMouseExited(evt);
            }
        });
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        sidePanel.add(homeButton);

        fcfsButton.setBackground(new java.awt.Color(43, 137, 253));
        fcfsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/fcfsicon.png"))); // NOI18N
        fcfsButton.setBorder(null);
        fcfsButton.setContentAreaFilled(false);
        fcfsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fcfsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fcfsButtonMouseExited(evt);
            }
        });
        fcfsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcfsButtonActionPerformed(evt);
            }
        });
        sidePanel.add(fcfsButton);

        sstfButton.setBackground(new java.awt.Color(43, 137, 253));
        sstfButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/sstficon.png"))); // NOI18N
        sstfButton.setBorder(null);
        sstfButton.setContentAreaFilled(false);
        sstfButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sstfButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sstfButtonMouseExited(evt);
            }
        });
        sstfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sstfButtonActionPerformed(evt);
            }
        });
        sidePanel.add(sstfButton);

        scanButton.setBackground(new java.awt.Color(43, 137, 253));
        scanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/scanicon.png"))); // NOI18N
        scanButton.setBorder(null);
        scanButton.setContentAreaFilled(false);
        scanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scanButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                scanButtonMouseExited(evt);
            }
        });
        scanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanButtonActionPerformed(evt);
            }
        });
        sidePanel.add(scanButton);

        cscanButton.setBackground(new java.awt.Color(43, 137, 253));
        cscanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/cscanicon.png"))); // NOI18N
        cscanButton.setBorder(null);
        cscanButton.setContentAreaFilled(false);
        cscanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cscanButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cscanButtonMouseExited(evt);
            }
        });
        cscanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cscanButtonActionPerformed(evt);
            }
        });
        sidePanel.add(cscanButton);

        lookButton.setBackground(new java.awt.Color(43, 137, 253));
        lookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/lookicon.png"))); // NOI18N
        lookButton.setBorder(null);
        lookButton.setContentAreaFilled(false);
        lookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lookButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lookButtonMouseExited(evt);
            }
        });
        lookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookButtonActionPerformed(evt);
            }
        });
        sidePanel.add(lookButton);

        clookButton.setBackground(new java.awt.Color(43, 137, 253));
        clookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/clookicon.png"))); // NOI18N
        clookButton.setBorder(null);
        clookButton.setContentAreaFilled(false);
        clookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clookButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clookButtonMouseExited(evt);
            }
        });
        clookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clookButtonActionPerformed(evt);
            }
        });
        sidePanel.add(clookButton);

        exitButton.setBackground(new java.awt.Color(43, 137, 253));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/exiticon.png"))); // NOI18N
        exitButton.setBorder(null);
        exitButton.setContentAreaFilled(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        sidePanel.add(exitButton);

        MainPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 600));

        contentPanel.setLayout(new java.awt.CardLayout());

        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/homePanel-2.png"))); // NOI18N
        homePanel.add(homebg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        contentPanel.add(homePanel, "card2");

        fcfsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diskTextField.setBorder(null);
        diskTextField.setOpaque(false);
        diskTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskTextFieldActionPerformed(evt);
            }
        });
        fcfsPanel.add(diskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 186, 130, 20));

        diskButton.setBorderPainted(false);
        diskButton.setContentAreaFilled(false);
        fcfsPanel.add(diskButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 180, 30, 30));

        clearDiskButton.setBorderPainted(false);
        clearDiskButton.setContentAreaFilled(false);
        fcfsPanel.add(clearDiskButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 30, 30));

        requestsTextField.setBorder(null);
        requestsTextField.setOpaque(false);
        requestsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestsTextFieldActionPerformed(evt);
            }
        });
        fcfsPanel.add(requestsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, 30));

        headButton.setBorderPainted(false);
        headButton.setContentAreaFilled(false);
        fcfsPanel.add(headButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 30, 30));

        clearButton.setBorderPainted(false);
        clearButton.setContentAreaFilled(false);
        fcfsPanel.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 30, 30));

        headTextField.setBorder(null);
        headTextField.setOpaque(false);
        headTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headTextFieldActionPerformed(evt);
            }
        });
        fcfsPanel.add(headTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 20));

        ioRequestsButton.setBorderPainted(false);
        ioRequestsButton.setContentAreaFilled(false);
        fcfsPanel.add(ioRequestsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 290, 30, 30));

        resetButton.setBorderPainted(false);
        resetButton.setContentAreaFilled(false);
        fcfsPanel.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 30, 30));

        calculateButton.setBorderPainted(false);
        calculateButton.setContentAreaFilled(false);
        fcfsPanel.add(calculateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 110, 30));

        tracksLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tracksLabel.setText("[tracks]");
        fcfsPanel.add(tracksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, 30));

        graphScrollPane.setBorder(null);

        javax.swing.GroupLayout graphPanel10Layout = new javax.swing.GroupLayout(graphPanel10);
        graphPanel10.setLayout(graphPanel10Layout);
        graphPanel10Layout.setHorizontalGroup(
            graphPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        graphPanel10Layout.setVerticalGroup(
            graphPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        graphScrollPane.setViewportView(graphPanel10);

        fcfsPanel.add(graphScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 440, 330));

        FCFSTableScrollPane.setOpaque(false);

        FCFSTable10.setBackground(new java.awt.Color(236, 240, 243));
        FCFSTable10.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        FCFSTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "    PROCESS", "IO/REQUESTS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FCFSTable10.setOpaque(false);
        FCFSTable10.getTableHeader().setReorderingAllowed(false);
        FCFSTableScrollPane.setViewportView(FCFSTable10);
        if (FCFSTable10.getColumnModel().getColumnCount() > 0) {
            FCFSTable10.getColumnModel().getColumn(1).setResizable(false);
        }

        fcfsPanel.add(FCFSTableScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 240, 150));

        resultsTextAreaScrollPane.setBorder(null);
        resultsTextAreaScrollPane.setOpaque(false);
        resultsTextAreaScrollPane.setViewport(null);

        resultsTextArea10.setBackground(new java.awt.Color(236, 240, 243));
        resultsTextArea10.setColumns(20);
        resultsTextArea10.setRows(5);
        resultsTextArea10.setBorder(null);
        resultsTextArea10.setOpaque(false);
        resultsTextAreaScrollPane.setViewportView(resultsTextArea10);

        fcfsPanel.add(resultsTextAreaScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 430, 130));

        fcfsbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/fcfspanel.png"))); // NOI18N
        fcfsPanel.add(fcfsbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        contentPanel.add(fcfsPanel, "card2");

        sstfPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diskTextField1.setBorder(null);
        diskTextField1.setOpaque(false);
        diskTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskTextField1ActionPerformed(evt);
            }
        });
        sstfPanel.add(diskTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 186, 130, 20));

        diskButton1.setBorderPainted(false);
        diskButton1.setContentAreaFilled(false);
        sstfPanel.add(diskButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 180, 30, 30));

        clearDiskButton1.setBorderPainted(false);
        clearDiskButton1.setContentAreaFilled(false);
        sstfPanel.add(clearDiskButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 30, 30));

        requestsTextField1.setBorder(null);
        requestsTextField1.setOpaque(false);
        requestsTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestsTextField1ActionPerformed(evt);
            }
        });
        sstfPanel.add(requestsTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, 30));

        headButton1.setBorderPainted(false);
        headButton1.setContentAreaFilled(false);
        sstfPanel.add(headButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 30, 30));

        clearButton1.setBorderPainted(false);
        clearButton1.setContentAreaFilled(false);
        sstfPanel.add(clearButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 30, 30));

        headTextField1.setBorder(null);
        headTextField1.setOpaque(false);
        headTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headTextField1ActionPerformed(evt);
            }
        });
        sstfPanel.add(headTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 20));

        ioRequestsButton1.setBorderPainted(false);
        ioRequestsButton1.setContentAreaFilled(false);
        sstfPanel.add(ioRequestsButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 290, 30, 30));

        resetButton1.setBorderPainted(false);
        resetButton1.setContentAreaFilled(false);
        sstfPanel.add(resetButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 30, 30));

        calculateButton1.setBorderPainted(false);
        calculateButton1.setContentAreaFilled(false);
        sstfPanel.add(calculateButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 110, 30));

        tracksLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tracksLabel1.setText("[tracks]");
        sstfPanel.add(tracksLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, 30));

        graphScrollPane1.setBorder(null);

        javax.swing.GroupLayout graphPanel9Layout = new javax.swing.GroupLayout(graphPanel9);
        graphPanel9.setLayout(graphPanel9Layout);
        graphPanel9Layout.setHorizontalGroup(
            graphPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        graphPanel9Layout.setVerticalGroup(
            graphPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        graphScrollPane1.setViewportView(graphPanel9);

        sstfPanel.add(graphScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 440, 330));

        FCFSTableScrollPane1.setOpaque(false);

        FCFSTable9.setBackground(new java.awt.Color(236, 240, 243));
        FCFSTable9.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        FCFSTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "    PROCESS", "IO/REQUESTS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FCFSTable9.setOpaque(false);
        FCFSTable9.getTableHeader().setReorderingAllowed(false);
        FCFSTableScrollPane1.setViewportView(FCFSTable9);
        if (FCFSTable9.getColumnModel().getColumnCount() > 0) {
            FCFSTable9.getColumnModel().getColumn(1).setResizable(false);
        }

        sstfPanel.add(FCFSTableScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 240, 150));

        resultsTextAreaScrollPane1.setBorder(null);
        resultsTextAreaScrollPane1.setOpaque(false);
        resultsTextAreaScrollPane1.setViewport(null);

        resultsTextArea9.setBackground(new java.awt.Color(236, 240, 243));
        resultsTextArea9.setColumns(20);
        resultsTextArea9.setRows(5);
        resultsTextArea9.setBorder(null);
        resultsTextArea9.setOpaque(false);
        resultsTextAreaScrollPane1.setViewportView(resultsTextArea9);

        sstfPanel.add(resultsTextAreaScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 430, 130));

        sstfbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/sstfpanel.png"))); // NOI18N
        sstfPanel.add(sstfbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        contentPanel.add(sstfPanel, "card2");

        scanPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diskTextField2.setBorder(null);
        diskTextField2.setOpaque(false);
        diskTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskTextField2ActionPerformed(evt);
            }
        });
        scanPanel.add(diskTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 186, 130, 20));

        diskButton2.setBorderPainted(false);
        diskButton2.setContentAreaFilled(false);
        scanPanel.add(diskButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 180, 30, 30));

        clearDiskButton2.setBorderPainted(false);
        clearDiskButton2.setContentAreaFilled(false);
        scanPanel.add(clearDiskButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 30, 30));

        requestsTextField2.setBorder(null);
        requestsTextField2.setOpaque(false);
        requestsTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestsTextField2ActionPerformed(evt);
            }
        });
        scanPanel.add(requestsTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, 30));

        headButton2.setBorderPainted(false);
        headButton2.setContentAreaFilled(false);
        scanPanel.add(headButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 30, 30));

        clearButton2.setBorderPainted(false);
        clearButton2.setContentAreaFilled(false);
        scanPanel.add(clearButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 30, 30));

        headTextField2.setBorder(null);
        headTextField2.setOpaque(false);
        headTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headTextField2ActionPerformed(evt);
            }
        });
        scanPanel.add(headTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 20));

        ioRequestsButton2.setBorderPainted(false);
        ioRequestsButton2.setContentAreaFilled(false);
        scanPanel.add(ioRequestsButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 290, 30, 30));

        resetButton2.setBorderPainted(false);
        resetButton2.setContentAreaFilled(false);
        scanPanel.add(resetButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 30, 30));

        calculateButton2.setBorderPainted(false);
        calculateButton2.setContentAreaFilled(false);
        scanPanel.add(calculateButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 110, 30));

        tracksLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tracksLabel2.setText("[tracks]");
        scanPanel.add(tracksLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, 30));

        graphScrollPane2.setBorder(null);

        javax.swing.GroupLayout graphPanel8Layout = new javax.swing.GroupLayout(graphPanel8);
        graphPanel8.setLayout(graphPanel8Layout);
        graphPanel8Layout.setHorizontalGroup(
            graphPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        graphPanel8Layout.setVerticalGroup(
            graphPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        graphScrollPane2.setViewportView(graphPanel8);

        scanPanel.add(graphScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 440, 330));

        FCFSTableScrollPane2.setOpaque(false);

        FCFSTable8.setBackground(new java.awt.Color(236, 240, 243));
        FCFSTable8.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        FCFSTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "    PROCESS", "IO/REQUESTS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FCFSTable8.setOpaque(false);
        FCFSTable8.getTableHeader().setReorderingAllowed(false);
        FCFSTableScrollPane2.setViewportView(FCFSTable8);
        if (FCFSTable8.getColumnModel().getColumnCount() > 0) {
            FCFSTable8.getColumnModel().getColumn(1).setResizable(false);
        }

        scanPanel.add(FCFSTableScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 240, 150));

        resultsTextAreaScrollPane2.setBorder(null);
        resultsTextAreaScrollPane2.setOpaque(false);
        resultsTextAreaScrollPane2.setViewport(null);

        resultsTextArea8.setBackground(new java.awt.Color(236, 240, 243));
        resultsTextArea8.setColumns(20);
        resultsTextArea8.setRows(5);
        resultsTextArea8.setBorder(null);
        resultsTextArea8.setOpaque(false);
        resultsTextAreaScrollPane2.setViewportView(resultsTextArea8);

        scanPanel.add(resultsTextAreaScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 430, 130));

        scanbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/scanpanel.png"))); // NOI18N
        scanPanel.add(scanbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        contentPanel.add(scanPanel, "card2");

        cscanPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diskTextField3.setBorder(null);
        diskTextField3.setOpaque(false);
        diskTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskTextField3ActionPerformed(evt);
            }
        });
        cscanPanel.add(diskTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 186, 130, 20));

        diskButton3.setBorderPainted(false);
        diskButton3.setContentAreaFilled(false);
        cscanPanel.add(diskButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 180, 30, 30));

        clearDiskButton3.setBorderPainted(false);
        clearDiskButton3.setContentAreaFilled(false);
        cscanPanel.add(clearDiskButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 30, 30));

        requestsTextField3.setBorder(null);
        requestsTextField3.setOpaque(false);
        requestsTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestsTextField3ActionPerformed(evt);
            }
        });
        cscanPanel.add(requestsTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, 30));

        headButton3.setBorderPainted(false);
        headButton3.setContentAreaFilled(false);
        cscanPanel.add(headButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 30, 30));

        clearButton3.setBorderPainted(false);
        clearButton3.setContentAreaFilled(false);
        cscanPanel.add(clearButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 30, 30));

        headTextField3.setBorder(null);
        headTextField3.setOpaque(false);
        headTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headTextField3ActionPerformed(evt);
            }
        });
        cscanPanel.add(headTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 20));

        ioRequestsButton3.setBorderPainted(false);
        ioRequestsButton3.setContentAreaFilled(false);
        cscanPanel.add(ioRequestsButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 290, 30, 30));

        resetButton3.setBorderPainted(false);
        resetButton3.setContentAreaFilled(false);
        cscanPanel.add(resetButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 30, 30));

        calculateButton3.setBorderPainted(false);
        calculateButton3.setContentAreaFilled(false);
        cscanPanel.add(calculateButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 110, 30));

        tracksLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tracksLabel3.setText("[tracks]");
        cscanPanel.add(tracksLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, 30));

        graphScrollPane3.setBorder(null);

        javax.swing.GroupLayout graphPanel7Layout = new javax.swing.GroupLayout(graphPanel7);
        graphPanel7.setLayout(graphPanel7Layout);
        graphPanel7Layout.setHorizontalGroup(
            graphPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        graphPanel7Layout.setVerticalGroup(
            graphPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        graphScrollPane3.setViewportView(graphPanel7);

        cscanPanel.add(graphScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 440, 330));

        FCFSTableScrollPane3.setOpaque(false);

        FCFSTable7.setBackground(new java.awt.Color(236, 240, 243));
        FCFSTable7.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        FCFSTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "    PROCESS", "IO/REQUESTS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FCFSTable7.setOpaque(false);
        FCFSTable7.getTableHeader().setReorderingAllowed(false);
        FCFSTableScrollPane3.setViewportView(FCFSTable7);
        if (FCFSTable7.getColumnModel().getColumnCount() > 0) {
            FCFSTable7.getColumnModel().getColumn(1).setResizable(false);
        }

        cscanPanel.add(FCFSTableScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 240, 150));

        resultsTextAreaScrollPane3.setBorder(null);
        resultsTextAreaScrollPane3.setOpaque(false);
        resultsTextAreaScrollPane3.setViewport(null);

        resultsTextArea7.setBackground(new java.awt.Color(236, 240, 243));
        resultsTextArea7.setColumns(20);
        resultsTextArea7.setRows(5);
        resultsTextArea7.setBorder(null);
        resultsTextArea7.setOpaque(false);
        resultsTextAreaScrollPane3.setViewportView(resultsTextArea7);

        cscanPanel.add(resultsTextAreaScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 430, 130));

        cscanbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/cscanpanel.png"))); // NOI18N
        cscanPanel.add(cscanbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        contentPanel.add(cscanPanel, "card2");

        lookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diskTextField4.setBorder(null);
        diskTextField4.setOpaque(false);
        diskTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskTextField4ActionPerformed(evt);
            }
        });
        lookPanel.add(diskTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 186, 130, 20));

        diskButton4.setBorderPainted(false);
        diskButton4.setContentAreaFilled(false);
        lookPanel.add(diskButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 180, 30, 30));

        clearDiskButton4.setBorderPainted(false);
        clearDiskButton4.setContentAreaFilled(false);
        lookPanel.add(clearDiskButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 30, 30));

        requestsTextField4.setBorder(null);
        requestsTextField4.setOpaque(false);
        requestsTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestsTextField4ActionPerformed(evt);
            }
        });
        lookPanel.add(requestsTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, 30));

        headButton4.setBorderPainted(false);
        headButton4.setContentAreaFilled(false);
        lookPanel.add(headButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 30, 30));

        clearButton4.setBorderPainted(false);
        clearButton4.setContentAreaFilled(false);
        lookPanel.add(clearButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 30, 30));

        headTextField4.setBorder(null);
        headTextField4.setOpaque(false);
        headTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headTextField4ActionPerformed(evt);
            }
        });
        lookPanel.add(headTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 20));

        ioRequestsButton4.setBorderPainted(false);
        ioRequestsButton4.setContentAreaFilled(false);
        lookPanel.add(ioRequestsButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 290, 30, 30));

        resetButton4.setBorderPainted(false);
        resetButton4.setContentAreaFilled(false);
        lookPanel.add(resetButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 30, 30));

        calculateButton4.setBorderPainted(false);
        calculateButton4.setContentAreaFilled(false);
        lookPanel.add(calculateButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 110, 30));

        tracksLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tracksLabel4.setText("[tracks]");
        lookPanel.add(tracksLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, 30));

        graphScrollPane4.setBorder(null);

        javax.swing.GroupLayout graphPanel6Layout = new javax.swing.GroupLayout(graphPanel6);
        graphPanel6.setLayout(graphPanel6Layout);
        graphPanel6Layout.setHorizontalGroup(
            graphPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        graphPanel6Layout.setVerticalGroup(
            graphPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        graphScrollPane4.setViewportView(graphPanel6);

        lookPanel.add(graphScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 440, 330));

        FCFSTableScrollPane4.setOpaque(false);

        FCFSTable6.setBackground(new java.awt.Color(236, 240, 243));
        FCFSTable6.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        FCFSTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "    PROCESS", "IO/REQUESTS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FCFSTable6.setOpaque(false);
        FCFSTable6.getTableHeader().setReorderingAllowed(false);
        FCFSTableScrollPane4.setViewportView(FCFSTable6);
        if (FCFSTable6.getColumnModel().getColumnCount() > 0) {
            FCFSTable6.getColumnModel().getColumn(1).setResizable(false);
        }

        lookPanel.add(FCFSTableScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 240, 150));

        resultsTextAreaScrollPane4.setBorder(null);
        resultsTextAreaScrollPane4.setOpaque(false);
        resultsTextAreaScrollPane4.setViewport(null);

        resultsTextArea6.setBackground(new java.awt.Color(236, 240, 243));
        resultsTextArea6.setColumns(20);
        resultsTextArea6.setRows(5);
        resultsTextArea6.setBorder(null);
        resultsTextArea6.setOpaque(false);
        resultsTextAreaScrollPane4.setViewportView(resultsTextArea6);

        lookPanel.add(resultsTextAreaScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 430, 130));

        lookbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/lookpanel.png"))); // NOI18N
        lookPanel.add(lookbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        contentPanel.add(lookPanel, "card2");

        clookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diskTextField5.setBorder(null);
        diskTextField5.setOpaque(false);
        diskTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskTextField5ActionPerformed(evt);
            }
        });
        clookPanel.add(diskTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 186, 130, 20));

        diskButton5.setBorderPainted(false);
        diskButton5.setContentAreaFilled(false);
        clookPanel.add(diskButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 180, 30, 30));

        clearDiskButton5.setBorderPainted(false);
        clearDiskButton5.setContentAreaFilled(false);
        clookPanel.add(clearDiskButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 30, 30));

        requestsTextField5.setBorder(null);
        requestsTextField5.setOpaque(false);
        requestsTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestsTextField5ActionPerformed(evt);
            }
        });
        clookPanel.add(requestsTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, 30));

        headButton5.setBorderPainted(false);
        headButton5.setContentAreaFilled(false);
        clookPanel.add(headButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 30, 30));

        clearButton5.setBorderPainted(false);
        clearButton5.setContentAreaFilled(false);
        clookPanel.add(clearButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 30, 30));

        headTextField5.setBorder(null);
        headTextField5.setOpaque(false);
        headTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headTextField5ActionPerformed(evt);
            }
        });
        clookPanel.add(headTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 20));

        ioRequestsButton5.setBorderPainted(false);
        ioRequestsButton5.setContentAreaFilled(false);
        clookPanel.add(ioRequestsButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 290, 30, 30));

        resetButton5.setBorderPainted(false);
        resetButton5.setContentAreaFilled(false);
        clookPanel.add(resetButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 30, 30));

        calculateButton5.setBorderPainted(false);
        calculateButton5.setContentAreaFilled(false);
        clookPanel.add(calculateButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 110, 30));

        tracksLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tracksLabel5.setText("[tracks]");
        clookPanel.add(tracksLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, 30));

        graphScrollPane5.setBorder(null);

        javax.swing.GroupLayout graphPanel5Layout = new javax.swing.GroupLayout(graphPanel5);
        graphPanel5.setLayout(graphPanel5Layout);
        graphPanel5Layout.setHorizontalGroup(
            graphPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        graphPanel5Layout.setVerticalGroup(
            graphPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        graphScrollPane5.setViewportView(graphPanel5);

        clookPanel.add(graphScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 440, 330));

        FCFSTableScrollPane5.setOpaque(false);

        FCFSTable5.setBackground(new java.awt.Color(236, 240, 243));
        FCFSTable5.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        FCFSTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "    PROCESS", "IO/REQUESTS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FCFSTable5.setOpaque(false);
        FCFSTable5.getTableHeader().setReorderingAllowed(false);
        FCFSTableScrollPane5.setViewportView(FCFSTable5);
        if (FCFSTable5.getColumnModel().getColumnCount() > 0) {
            FCFSTable5.getColumnModel().getColumn(1).setResizable(false);
        }

        clookPanel.add(FCFSTableScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 240, 150));

        resultsTextAreaScrollPane5.setBorder(null);
        resultsTextAreaScrollPane5.setOpaque(false);
        resultsTextAreaScrollPane5.setViewport(null);

        resultsTextArea5.setBackground(new java.awt.Color(236, 240, 243));
        resultsTextArea5.setColumns(20);
        resultsTextArea5.setRows(5);
        resultsTextArea5.setBorder(null);
        resultsTextArea5.setOpaque(false);
        resultsTextAreaScrollPane5.setViewportView(resultsTextArea5);

        clookPanel.add(resultsTextAreaScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 430, 130));

        clookbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/clookpanel.png"))); // NOI18N
        clookPanel.add(clookbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        contentPanel.add(clookPanel, "card2");

        MainPanel.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 800, 600));

        mainbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscase2/case2frame.png"))); // NOI18N
        MainPanel.add(mainbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diskTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskTextFieldActionPerformed

    private void requestsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestsTextFieldActionPerformed

    private void headTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headTextFieldActionPerformed

    private void diskTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskTextField1ActionPerformed

    private void requestsTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestsTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestsTextField1ActionPerformed

    private void headTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headTextField1ActionPerformed

    private void diskTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskTextField2ActionPerformed

    private void requestsTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestsTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestsTextField2ActionPerformed

    private void headTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headTextField2ActionPerformed

    private void diskTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskTextField3ActionPerformed

    private void requestsTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestsTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestsTextField3ActionPerformed

    private void headTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headTextField3ActionPerformed

    private void diskTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskTextField4ActionPerformed

    private void requestsTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestsTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestsTextField4ActionPerformed

    private void headTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headTextField4ActionPerformed

    private void diskTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskTextField5ActionPerformed

    private void requestsTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestsTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestsTextField5ActionPerformed

    private void headTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headTextField5ActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        //clearing panel
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel. revalidate();
        
        //adding panels
        contentPanel.add(homePanel);
        contentPanel.repaint();
        contentPanel. revalidate();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void fcfsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcfsButtonActionPerformed
        //clearing panel
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel. revalidate();
        
        //adding panels
        contentPanel.add(fcfsPanel);
        contentPanel.repaint();
        contentPanel. revalidate();
    }//GEN-LAST:event_fcfsButtonActionPerformed

    private void sstfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sstfButtonActionPerformed
        //clearing panel
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel. revalidate();
        
        //adding panels
        contentPanel.add(sstfPanel);
        contentPanel.repaint();
        contentPanel. revalidate();
    }//GEN-LAST:event_sstfButtonActionPerformed

    private void scanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanButtonActionPerformed
        //clearing panel
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel. revalidate();
        
        //adding panels
        contentPanel.add(scanPanel);
        contentPanel.repaint();
        contentPanel. revalidate();
    }//GEN-LAST:event_scanButtonActionPerformed

    private void cscanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cscanButtonActionPerformed
        //clearing panel
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel. revalidate();
        
        //adding panels
        contentPanel.add(cscanPanel);
        contentPanel.repaint();
        contentPanel. revalidate();
    }//GEN-LAST:event_cscanButtonActionPerformed

    private void lookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookButtonActionPerformed
        //clearing panel
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel. revalidate();
        
        //adding panels
        contentPanel.add(lookPanel);
        contentPanel.repaint();
        contentPanel. revalidate();
    }//GEN-LAST:event_lookButtonActionPerformed

    private void clookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clookButtonActionPerformed
        //clearing panel
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel. revalidate();
        
        //adding panels
        contentPanel.add(clookPanel);
        contentPanel.repaint();
        contentPanel. revalidate();
    }//GEN-LAST:event_clookButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
                int button = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm exit", JOptionPane.YES_NO_OPTION);

        if (button != JOptionPane.YES_OPTION) {
            return;
        }

        dispose();
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void homeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseEntered
        homeButton.setOpaque(true);
    }//GEN-LAST:event_homeButtonMouseEntered

    private void fcfsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fcfsButtonMouseEntered
        fcfsButton.setOpaque(true);
    }//GEN-LAST:event_fcfsButtonMouseEntered

    private void sstfButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sstfButtonMouseEntered
        sstfButton.setOpaque(true);
    }//GEN-LAST:event_sstfButtonMouseEntered

    private void scanButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanButtonMouseEntered
        scanButton.setOpaque(true);
    }//GEN-LAST:event_scanButtonMouseEntered

    private void cscanButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cscanButtonMouseEntered
        cscanButton.setOpaque(true);
    }//GEN-LAST:event_cscanButtonMouseEntered

    private void lookButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lookButtonMouseEntered
        lookButton.setOpaque(true);
    }//GEN-LAST:event_lookButtonMouseEntered

    private void clookButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clookButtonMouseEntered
        clookButton.setOpaque(true);
    }//GEN-LAST:event_clookButtonMouseEntered

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        exitButton.setOpaque(true);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void fcfsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fcfsButtonMouseExited
        fcfsButton.setOpaque(false);
    }//GEN-LAST:event_fcfsButtonMouseExited

    private void homeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseExited
        homeButton.setOpaque(false);
    }//GEN-LAST:event_homeButtonMouseExited

    private void sstfButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sstfButtonMouseExited
        sstfButton.setOpaque(false);
    }//GEN-LAST:event_sstfButtonMouseExited

    private void scanButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanButtonMouseExited
        scanButton.setOpaque(false);
    }//GEN-LAST:event_scanButtonMouseExited

    private void cscanButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cscanButtonMouseExited
        cscanButton.setOpaque(false);
    }//GEN-LAST:event_cscanButtonMouseExited

    private void lookButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lookButtonMouseExited
       lookButton.setOpaque(false);
    }//GEN-LAST:event_lookButtonMouseExited

    private void clookButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clookButtonMouseExited
        clookButton.setOpaque(false);
    }//GEN-LAST:event_clookButtonMouseExited

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
       exitButton.setOpaque(false);
    }//GEN-LAST:event_exitButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FCFSTable10;
    private javax.swing.JTable FCFSTable5;
    private javax.swing.JTable FCFSTable6;
    private javax.swing.JTable FCFSTable7;
    private javax.swing.JTable FCFSTable8;
    private javax.swing.JTable FCFSTable9;
    private javax.swing.JScrollPane FCFSTableScrollPane;
    private javax.swing.JScrollPane FCFSTableScrollPane1;
    private javax.swing.JScrollPane FCFSTableScrollPane2;
    private javax.swing.JScrollPane FCFSTableScrollPane3;
    private javax.swing.JScrollPane FCFSTableScrollPane4;
    private javax.swing.JScrollPane FCFSTableScrollPane5;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton calculateButton1;
    private javax.swing.JButton calculateButton2;
    private javax.swing.JButton calculateButton3;
    private javax.swing.JButton calculateButton4;
    private javax.swing.JButton calculateButton5;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton clearButton1;
    private javax.swing.JButton clearButton2;
    private javax.swing.JButton clearButton3;
    private javax.swing.JButton clearButton4;
    private javax.swing.JButton clearButton5;
    private javax.swing.JButton clearDiskButton;
    private javax.swing.JButton clearDiskButton1;
    private javax.swing.JButton clearDiskButton2;
    private javax.swing.JButton clearDiskButton3;
    private javax.swing.JButton clearDiskButton4;
    private javax.swing.JButton clearDiskButton5;
    private javax.swing.JButton clookButton;
    private javax.swing.JPanel clookPanel;
    private javax.swing.JLabel clookbg;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton cscanButton;
    private javax.swing.JPanel cscanPanel;
    private javax.swing.JLabel cscanbg;
    private javax.swing.JButton diskButton;
    private javax.swing.JButton diskButton1;
    private javax.swing.JButton diskButton2;
    private javax.swing.JButton diskButton3;
    private javax.swing.JButton diskButton4;
    private javax.swing.JButton diskButton5;
    private javax.swing.JTextField diskTextField;
    private javax.swing.JTextField diskTextField1;
    private javax.swing.JTextField diskTextField2;
    private javax.swing.JTextField diskTextField3;
    private javax.swing.JTextField diskTextField4;
    private javax.swing.JTextField diskTextField5;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton fcfsButton;
    private javax.swing.JPanel fcfsPanel;
    private javax.swing.JLabel fcfsbg;
    private javax.swing.JPanel graphPanel10;
    private javax.swing.JPanel graphPanel5;
    private javax.swing.JPanel graphPanel6;
    private javax.swing.JPanel graphPanel7;
    private javax.swing.JPanel graphPanel8;
    private javax.swing.JPanel graphPanel9;
    private javax.swing.JScrollPane graphScrollPane;
    private javax.swing.JScrollPane graphScrollPane1;
    private javax.swing.JScrollPane graphScrollPane2;
    private javax.swing.JScrollPane graphScrollPane3;
    private javax.swing.JScrollPane graphScrollPane4;
    private javax.swing.JScrollPane graphScrollPane5;
    private javax.swing.JButton headButton;
    private javax.swing.JButton headButton1;
    private javax.swing.JButton headButton2;
    private javax.swing.JButton headButton3;
    private javax.swing.JButton headButton4;
    private javax.swing.JButton headButton5;
    private javax.swing.JTextField headTextField;
    private javax.swing.JTextField headTextField1;
    private javax.swing.JTextField headTextField2;
    private javax.swing.JTextField headTextField3;
    private javax.swing.JTextField headTextField4;
    private javax.swing.JTextField headTextField5;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel homebg;
    private javax.swing.JButton ioRequestsButton;
    private javax.swing.JButton ioRequestsButton1;
    private javax.swing.JButton ioRequestsButton2;
    private javax.swing.JButton ioRequestsButton3;
    private javax.swing.JButton ioRequestsButton4;
    private javax.swing.JButton ioRequestsButton5;
    private javax.swing.JButton lookButton;
    private javax.swing.JPanel lookPanel;
    private javax.swing.JLabel lookbg;
    private javax.swing.JLabel mainbg;
    private javax.swing.JTextField requestsTextField;
    private javax.swing.JTextField requestsTextField1;
    private javax.swing.JTextField requestsTextField2;
    private javax.swing.JTextField requestsTextField3;
    private javax.swing.JTextField requestsTextField4;
    private javax.swing.JTextField requestsTextField5;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton resetButton1;
    private javax.swing.JButton resetButton2;
    private javax.swing.JButton resetButton3;
    private javax.swing.JButton resetButton4;
    private javax.swing.JButton resetButton5;
    private javax.swing.JTextArea resultsTextArea10;
    private javax.swing.JTextArea resultsTextArea5;
    private javax.swing.JTextArea resultsTextArea6;
    private javax.swing.JTextArea resultsTextArea7;
    private javax.swing.JTextArea resultsTextArea8;
    private javax.swing.JTextArea resultsTextArea9;
    private javax.swing.JScrollPane resultsTextAreaScrollPane;
    private javax.swing.JScrollPane resultsTextAreaScrollPane1;
    private javax.swing.JScrollPane resultsTextAreaScrollPane2;
    private javax.swing.JScrollPane resultsTextAreaScrollPane3;
    private javax.swing.JScrollPane resultsTextAreaScrollPane4;
    private javax.swing.JScrollPane resultsTextAreaScrollPane5;
    private javax.swing.JButton scanButton;
    private javax.swing.JPanel scanPanel;
    private javax.swing.JLabel scanbg;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton sstfButton;
    private javax.swing.JPanel sstfPanel;
    private javax.swing.JLabel sstfbg;
    private javax.swing.JLabel tracksLabel;
    private javax.swing.JLabel tracksLabel1;
    private javax.swing.JLabel tracksLabel2;
    private javax.swing.JLabel tracksLabel3;
    private javax.swing.JLabel tracksLabel4;
    private javax.swing.JLabel tracksLabel5;
    // End of variables declaration//GEN-END:variables
}
