/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JOptionPane;

/**
 *
 * @author casti
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        firstFitButton = new javax.swing.JButton();
        bestFitButton = new javax.swing.JButton();
        worstFitButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        bgcontent1 = new javax.swing.JLabel();
        worstFitPanel = new javax.swing.JPanel();
        setOsSize = new javax.swing.JButton();
        osInput = new javax.swing.JTextField();
        ganttPane3 = new javax.swing.JScrollPane();
        ganttPanel = new javax.swing.JPanel();
        calculate3 = new javax.swing.JButton();
        clearPartition3 = new javax.swing.JButton();
        clearProcess3 = new javax.swing.JButton();
        addPartition3 = new javax.swing.JButton();
        setMemorySize3 = new javax.swing.JButton();
        usedMemory3 = new javax.swing.JLabel();
        osSize = new javax.swing.JLabel();
        remainingMemory4 = new javax.swing.JLabel();
        partitionPane3 = new javax.swing.JScrollPane();
        partitionTable3 = new javax.swing.JTable();
        processPane3 = new javax.swing.JScrollPane();
        processTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        partitionSize3 = new javax.swing.JTextField();
        memorySize3 = new javax.swing.JTextField();
        addProcess3 = new javax.swing.JButton();
        processSize3 = new javax.swing.JTextField();
        bgcontent3 = new javax.swing.JLabel();
        bestFitPanel = new javax.swing.JPanel();
        ganttPane2 = new javax.swing.JScrollPane();
        calculate2 = new javax.swing.JButton();
        clearPartition2 = new javax.swing.JButton();
        clearProcess2 = new javax.swing.JButton();
        addPartition2 = new javax.swing.JButton();
        setMemorySize2 = new javax.swing.JButton();
        usedMemory2 = new javax.swing.JLabel();
        remainingMemory2 = new javax.swing.JLabel();
        partitionPane2 = new javax.swing.JScrollPane();
        partitionTable2 = new javax.swing.JTable();
        processPane2 = new javax.swing.JScrollPane();
        processTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        partitionSize2 = new javax.swing.JTextField();
        memorySize2 = new javax.swing.JTextField();
        addProcess2 = new javax.swing.JButton();
        processSize2 = new javax.swing.JTextField();
        bgcontent2 = new javax.swing.JLabel();
        firstFitPanel = new javax.swing.JPanel();
        ganttPane = new javax.swing.JScrollPane();
        calculate = new javax.swing.JButton();
        clearPartition = new javax.swing.JButton();
        clearProcess = new javax.swing.JButton();
        addPartition = new javax.swing.JButton();
        setMemorySize = new javax.swing.JButton();
        usedMemory = new javax.swing.JLabel();
        remainingMemory = new javax.swing.JLabel();
        partitionPane = new javax.swing.JScrollPane();
        partitionTable = new javax.swing.JTable();
        processPane = new javax.swing.JScrollPane();
        processTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        partitionSize = new javax.swing.JTextField();
        memorySize = new javax.swing.JTextField();
        addProcess = new javax.swing.JButton();
        processSize = new javax.swing.JTextField();
        bgcontent = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setBackground(new java.awt.Color(43, 137, 253));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorymanagement/exitbutton.png"))); // NOI18N
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 140, 90));

        homeButton.setBackground(new java.awt.Color(43, 137, 253));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorymanagement/homebutton.png"))); // NOI18N
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButtonMouseExited(evt);
            }
        });
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 140, 90));

        firstFitButton.setBackground(new java.awt.Color(43, 137, 253));
        firstFitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorymanagement/firstfitbutton.png"))); // NOI18N
        firstFitButton.setBorderPainted(false);
        firstFitButton.setContentAreaFilled(false);
        firstFitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                firstFitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                firstFitButtonMouseExited(evt);
            }
        });
        firstFitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstFitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(firstFitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 140, 90));

        bestFitButton.setBackground(new java.awt.Color(43, 137, 253));
        bestFitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorymanagement/bestfitbutton.png"))); // NOI18N
        bestFitButton.setBorderPainted(false);
        bestFitButton.setContentAreaFilled(false);
        bestFitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bestFitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bestFitButtonMouseExited(evt);
            }
        });
        bestFitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestFitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(bestFitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 140, 90));

        worstFitButton.setBackground(new java.awt.Color(43, 137, 253));
        worstFitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorymanagement/worstfitbutton.png"))); // NOI18N
        worstFitButton.setBorderPainted(false);
        worstFitButton.setContentAreaFilled(false);
        worstFitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                worstFitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                worstFitButtonMouseExited(evt);
            }
        });
        worstFitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worstFitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(worstFitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 140, 90));

        contentPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        contentPanel.setLayout(new java.awt.CardLayout());

        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgcontent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorymanagement/homePanel.png"))); // NOI18N
        homePanel.add(bgcontent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        contentPanel.add(homePanel, "card3");

        worstFitPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        worstFitPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        worstFitPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        worstFitPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setOsSize.setBorderPainted(false);
        setOsSize.setContentAreaFilled(false);
        worstFitPanel.add(setOsSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 30, 30));

        osInput.setBorder(null);
        osInput.setOpaque(false);
        osInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osInputActionPerformed(evt);
            }
        });
        worstFitPanel.add(osInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 140, 30));

        ganttPane3.setBackground(new java.awt.Color(236, 240, 243));
        ganttPane3.setBorder(null);
        ganttPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ganttPane3.setOpaque(false);

        javax.swing.GroupLayout ganttPanelLayout = new javax.swing.GroupLayout(ganttPanel);
        ganttPanel.setLayout(ganttPanelLayout);
        ganttPanelLayout.setHorizontalGroup(
            ganttPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        ganttPanelLayout.setVerticalGroup(
            ganttPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        ganttPane3.setViewportView(ganttPanel);

        worstFitPanel.add(ganttPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 350, 60));

        calculate3.setBorderPainted(false);
        calculate3.setContentAreaFilled(false);
        worstFitPanel.add(calculate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 80, 70));

        clearPartition3.setBorderPainted(false);
        clearPartition3.setContentAreaFilled(false);
        worstFitPanel.add(clearPartition3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 40, 30));

        clearProcess3.setBorderPainted(false);
        clearProcess3.setContentAreaFilled(false);
        worstFitPanel.add(clearProcess3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 40, 30));

        addPartition3.setBorderPainted(false);
        addPartition3.setContentAreaFilled(false);
        worstFitPanel.add(addPartition3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 40, 30));

        setMemorySize3.setBorderPainted(false);
        setMemorySize3.setContentAreaFilled(false);
        worstFitPanel.add(setMemorySize3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 30, 30));

        usedMemory3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        worstFitPanel.add(usedMemory3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 80, 20));

        osSize.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        worstFitPanel.add(osSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 80, 20));

        remainingMemory4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        worstFitPanel.add(remainingMemory4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 80, 20));

        partitionTable3.setBackground(new java.awt.Color(236, 240, 243));
        partitionTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Partition", "Size"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        partitionTable3.setOpaque(false);
        partitionTable3.getTableHeader().setResizingAllowed(false);
        partitionTable3.getTableHeader().setReorderingAllowed(false);
        partitionPane3.setViewportView(partitionTable3);

        worstFitPanel.add(partitionPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 220, 300));

        processTable3.setBackground(new java.awt.Color(236, 240, 243));
        processTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Process", "Size"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        processTable3.setOpaque(false);
        processTable3.getTableHeader().setResizingAllowed(false);
        processTable3.getTableHeader().setReorderingAllowed(false);
        processPane3.setViewportView(processTable3);

        worstFitPanel.add(processPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 220, 300));

        jScrollPane4.setBackground(new java.awt.Color(236, 240, 243));
        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(236, 240, 243));
        jTextArea4.setColumns(15);
        jTextArea4.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        worstFitPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 190, 130));

        partitionSize3.setBorder(null);
        partitionSize3.setOpaque(false);
        partitionSize3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partitionSize3ActionPerformed(evt);
            }
        });
        worstFitPanel.add(partitionSize3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 180, 40));

        memorySize3.setBorder(null);
        memorySize3.setOpaque(false);
        memorySize3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memorySize3ActionPerformed(evt);
            }
        });
        worstFitPanel.add(memorySize3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 140, 30));

        addProcess3.setBorderPainted(false);
        addProcess3.setContentAreaFilled(false);
        worstFitPanel.add(addProcess3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 40, 30));

        processSize3.setBorder(null);
        processSize3.setOpaque(false);
        processSize3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processSize3ActionPerformed(evt);
            }
        });
        worstFitPanel.add(processSize3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 180, 40));

        bgcontent3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorymanagement/worstfitpanel.png"))); // NOI18N
        bgcontent3.setMaximumSize(new java.awt.Dimension(800, 600));
        bgcontent3.setMinimumSize(new java.awt.Dimension(800, 600));
        bgcontent3.setPreferredSize(new java.awt.Dimension(800, 600));
        worstFitPanel.add(bgcontent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        contentPanel.add(worstFitPanel, "card3");

        bestFitPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        bestFitPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        bestFitPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        bestFitPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ganttPane2.setBackground(new java.awt.Color(236, 240, 243));
        ganttPane2.setBorder(null);
        ganttPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ganttPane2.setOpaque(false);
        bestFitPanel.add(ganttPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 350, 60));

        calculate2.setBorderPainted(false);
        calculate2.setContentAreaFilled(false);
        bestFitPanel.add(calculate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 80, 70));

        clearPartition2.setBorderPainted(false);
        clearPartition2.setContentAreaFilled(false);
        bestFitPanel.add(clearPartition2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 40, 30));

        clearProcess2.setBorderPainted(false);
        clearProcess2.setContentAreaFilled(false);
        bestFitPanel.add(clearProcess2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 40, 30));

        addPartition2.setBorderPainted(false);
        addPartition2.setContentAreaFilled(false);
        bestFitPanel.add(addPartition2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 40, 30));

        setMemorySize2.setBorderPainted(false);
        setMemorySize2.setContentAreaFilled(false);
        bestFitPanel.add(setMemorySize2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 30, 30));

        usedMemory2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bestFitPanel.add(usedMemory2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 110, 20));

        remainingMemory2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bestFitPanel.add(remainingMemory2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 60, 20));

        partitionTable2.setBackground(new java.awt.Color(236, 240, 243));
        partitionTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Partition", "Size"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        partitionTable2.setOpaque(false);
        partitionTable2.getTableHeader().setResizingAllowed(false);
        partitionTable2.getTableHeader().setReorderingAllowed(false);
        partitionPane2.setViewportView(partitionTable2);

        bestFitPanel.add(partitionPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 220, 300));

        processTable2.setBackground(new java.awt.Color(236, 240, 243));
        processTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Process", "Size"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        processTable2.setOpaque(false);
        processTable2.getTableHeader().setResizingAllowed(false);
        processTable2.getTableHeader().setReorderingAllowed(false);
        processPane2.setViewportView(processTable2);

        bestFitPanel.add(processPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 220, 300));

        jScrollPane3.setBackground(new java.awt.Color(236, 240, 243));
        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(236, 240, 243));
        jTextArea3.setColumns(15);
        jTextArea3.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        bestFitPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 190, 200));

        partitionSize2.setBorder(null);
        partitionSize2.setOpaque(false);
        partitionSize2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partitionSize2ActionPerformed(evt);
            }
        });
        bestFitPanel.add(partitionSize2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 180, 40));

        memorySize2.setBorder(null);
        memorySize2.setOpaque(false);
        memorySize2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memorySize2ActionPerformed(evt);
            }
        });
        bestFitPanel.add(memorySize2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, 30));

        addProcess2.setBorderPainted(false);
        addProcess2.setContentAreaFilled(false);
        bestFitPanel.add(addProcess2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 40, 30));

        processSize2.setBorder(null);
        processSize2.setOpaque(false);
        processSize2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processSize2ActionPerformed(evt);
            }
        });
        bestFitPanel.add(processSize2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 180, 40));

        bgcontent2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorymanagement/bestfitpanel.png"))); // NOI18N
        bgcontent2.setMaximumSize(new java.awt.Dimension(800, 600));
        bgcontent2.setMinimumSize(new java.awt.Dimension(800, 600));
        bgcontent2.setPreferredSize(new java.awt.Dimension(800, 600));
        bestFitPanel.add(bgcontent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        contentPanel.add(bestFitPanel, "card4");

        firstFitPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        firstFitPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        firstFitPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        firstFitPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ganttPane.setBackground(new java.awt.Color(236, 240, 243));
        ganttPane.setBorder(null);
        ganttPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ganttPane.setOpaque(false);
        firstFitPanel.add(ganttPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 350, 60));

        calculate.setBorderPainted(false);
        calculate.setContentAreaFilled(false);
        firstFitPanel.add(calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 80, 70));

        clearPartition.setBorderPainted(false);
        clearPartition.setContentAreaFilled(false);
        firstFitPanel.add(clearPartition, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 40, 30));

        clearProcess.setBorderPainted(false);
        clearProcess.setContentAreaFilled(false);
        firstFitPanel.add(clearProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 40, 30));

        addPartition.setBorderPainted(false);
        addPartition.setContentAreaFilled(false);
        firstFitPanel.add(addPartition, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 40, 30));

        setMemorySize.setBorderPainted(false);
        setMemorySize.setContentAreaFilled(false);
        firstFitPanel.add(setMemorySize, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 30, 30));

        usedMemory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        firstFitPanel.add(usedMemory, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 110, 20));

        remainingMemory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        firstFitPanel.add(remainingMemory, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 60, 20));

        partitionTable.setBackground(new java.awt.Color(236, 240, 243));
        partitionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Partition", "Size"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        partitionTable.setOpaque(false);
        partitionTable.getTableHeader().setResizingAllowed(false);
        partitionTable.getTableHeader().setReorderingAllowed(false);
        partitionPane.setViewportView(partitionTable);

        firstFitPanel.add(partitionPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 220, 300));

        processTable.setBackground(new java.awt.Color(236, 240, 243));
        processTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Process", "Size"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        processTable.setOpaque(false);
        processTable.getTableHeader().setResizingAllowed(false);
        processTable.getTableHeader().setReorderingAllowed(false);
        processPane.setViewportView(processTable);

        firstFitPanel.add(processPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 220, 300));

        jScrollPane1.setBackground(new java.awt.Color(236, 240, 243));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(236, 240, 243));
        jTextArea1.setColumns(15);
        jTextArea1.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        firstFitPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 190, 200));

        partitionSize.setBorder(null);
        partitionSize.setOpaque(false);
        partitionSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partitionSizeActionPerformed(evt);
            }
        });
        firstFitPanel.add(partitionSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 180, 40));

        memorySize.setBorder(null);
        memorySize.setOpaque(false);
        memorySize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memorySizeActionPerformed(evt);
            }
        });
        firstFitPanel.add(memorySize, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, 30));

        addProcess.setBorderPainted(false);
        addProcess.setContentAreaFilled(false);
        firstFitPanel.add(addProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 40, 30));

        processSize.setBorder(null);
        processSize.setOpaque(false);
        processSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processSizeActionPerformed(evt);
            }
        });
        firstFitPanel.add(processSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 180, 40));

        bgcontent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorymanagement/firstfitpanel.png"))); // NOI18N
        bgcontent.setMaximumSize(new java.awt.Dimension(800, 600));
        bgcontent.setMinimumSize(new java.awt.Dimension(800, 600));
        bgcontent.setPreferredSize(new java.awt.Dimension(800, 600));
        firstFitPanel.add(bgcontent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        contentPanel.add(firstFitPanel, "card2");

        jPanel1.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 800, 590));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorymanagement/homebg.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void partitionSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partitionSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partitionSizeActionPerformed

    private void memorySizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memorySizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memorySizeActionPerformed

    private void processSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processSizeActionPerformed

    private void partitionSize2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partitionSize2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partitionSize2ActionPerformed

    private void memorySize2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memorySize2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memorySize2ActionPerformed

    private void processSize2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processSize2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processSize2ActionPerformed

    private void homeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseEntered
        homeButton.setOpaque(true);
    }//GEN-LAST:event_homeButtonMouseEntered

    private void firstFitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstFitButtonMouseEntered
        firstFitButton.setOpaque(true);
    }//GEN-LAST:event_firstFitButtonMouseEntered

    private void bestFitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bestFitButtonMouseEntered
        bestFitButton.setOpaque(true);
    }//GEN-LAST:event_bestFitButtonMouseEntered

    private void worstFitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_worstFitButtonMouseEntered
        worstFitButton.setOpaque(true);
    }//GEN-LAST:event_worstFitButtonMouseEntered

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        exitButton.setOpaque(true);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void homeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseExited
        homeButton.setOpaque(false);
    }//GEN-LAST:event_homeButtonMouseExited

    private void firstFitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstFitButtonMouseExited
        firstFitButton.setOpaque(false);
    }//GEN-LAST:event_firstFitButtonMouseExited

    private void bestFitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bestFitButtonMouseExited
        bestFitButton.setOpaque(false);
    }//GEN-LAST:event_bestFitButtonMouseExited

    private void worstFitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_worstFitButtonMouseExited
        worstFitButton.setOpaque(false);
    }//GEN-LAST:event_worstFitButtonMouseExited

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        exitButton.setOpaque(false);
    }//GEN-LAST:event_exitButtonMouseExited

    private void firstFitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstFitButtonActionPerformed
        
        //clearing panel
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel. revalidate();
        
        //adding panels
        contentPanel.add(firstFitPanel);
        contentPanel.repaint();
        contentPanel. revalidate();
    }//GEN-LAST:event_firstFitButtonActionPerformed

    private void bestFitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestFitButtonActionPerformed
        
        //clearing panel
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel. revalidate();
        
        //adding panels
        contentPanel.add(bestFitPanel);
        contentPanel.repaint();
        contentPanel. revalidate();
    }//GEN-LAST:event_bestFitButtonActionPerformed

    private void worstFitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worstFitButtonActionPerformed
        //clearing panel
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel. revalidate();
        
        //adding panels
        contentPanel.add(worstFitPanel);
        contentPanel.repaint();
        contentPanel. revalidate();
    }//GEN-LAST:event_worstFitButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        
        //clearing panel
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel. revalidate();
        
        //adding panels
        contentPanel.add(homePanel);
        contentPanel.repaint();
        contentPanel. revalidate();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        int button = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm exit", JOptionPane.YES_NO_OPTION);

        if (button != JOptionPane.YES_OPTION) {
            return;
        }

        dispose();
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void partitionSize3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partitionSize3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partitionSize3ActionPerformed

    private void memorySize3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memorySize3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memorySize3ActionPerformed

    private void processSize3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processSize3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processSize3ActionPerformed

    private void osInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_osInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPartition;
    private javax.swing.JButton addPartition2;
    private javax.swing.JButton addPartition3;
    private javax.swing.JButton addProcess;
    private javax.swing.JButton addProcess2;
    private javax.swing.JButton addProcess3;
    private javax.swing.JButton bestFitButton;
    private javax.swing.JPanel bestFitPanel;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bgcontent;
    private javax.swing.JLabel bgcontent1;
    private javax.swing.JLabel bgcontent2;
    private javax.swing.JLabel bgcontent3;
    private javax.swing.JButton calculate;
    private javax.swing.JButton calculate2;
    private javax.swing.JButton calculate3;
    private javax.swing.JButton clearPartition;
    private javax.swing.JButton clearPartition2;
    private javax.swing.JButton clearPartition3;
    private javax.swing.JButton clearProcess;
    private javax.swing.JButton clearProcess2;
    private javax.swing.JButton clearProcess3;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton firstFitButton;
    private javax.swing.JPanel firstFitPanel;
    private javax.swing.JScrollPane ganttPane;
    private javax.swing.JScrollPane ganttPane2;
    private javax.swing.JScrollPane ganttPane3;
    private javax.swing.JPanel ganttPanel;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField memorySize;
    private javax.swing.JTextField memorySize2;
    private javax.swing.JTextField memorySize3;
    private javax.swing.JTextField osInput;
    private javax.swing.JLabel osSize;
    private javax.swing.JScrollPane partitionPane;
    private javax.swing.JScrollPane partitionPane2;
    private javax.swing.JScrollPane partitionPane3;
    private javax.swing.JTextField partitionSize;
    private javax.swing.JTextField partitionSize2;
    private javax.swing.JTextField partitionSize3;
    private javax.swing.JTable partitionTable;
    private javax.swing.JTable partitionTable2;
    private javax.swing.JTable partitionTable3;
    private javax.swing.JScrollPane processPane;
    private javax.swing.JScrollPane processPane2;
    private javax.swing.JScrollPane processPane3;
    private javax.swing.JTextField processSize;
    private javax.swing.JTextField processSize2;
    private javax.swing.JTextField processSize3;
    private javax.swing.JTable processTable;
    private javax.swing.JTable processTable2;
    private javax.swing.JTable processTable3;
    private javax.swing.JLabel remainingMemory;
    private javax.swing.JLabel remainingMemory2;
    private javax.swing.JLabel remainingMemory4;
    private javax.swing.JButton setMemorySize;
    private javax.swing.JButton setMemorySize2;
    private javax.swing.JButton setMemorySize3;
    private javax.swing.JButton setOsSize;
    private javax.swing.JLabel usedMemory;
    private javax.swing.JLabel usedMemory2;
    private javax.swing.JLabel usedMemory3;
    private javax.swing.JButton worstFitButton;
    private javax.swing.JPanel worstFitPanel;
    // End of variables declaration//GEN-END:variables
}
